### ISSUE TITLE
Getting the private key

### ISSUE THREAD

**Issue by kbalint** [PKISharp/ACMESharpCore#10]
Hi, first of all, thanks for this library, it's a huge timesaver. 
I did a peak at the Tests, and found the CLI version quite good. 
In it there's a comment that states ExportKey has not enough support in .Net Core/Standard. 
I found it out when trying to do a  RSA.FromXmlString, it throws a PlatformNotSupported exception. 
Any chance here to somehow convert / reconstruct the 6-CertKey file from JSON to a PEM (?) or something 'edible' for OpenSSL to do the pfx conversion as a workaround?

**Comment by ebekker** [comment]
Great, glad I can help!

You pby want to take a look at the [SimplePKI](https://github.com/PKISharp/ACMESharpCore/tree/master/src/PKISharp.SimplePKI) library of this project, it has a number of useful operations that would be common when working with certs and various PKI components.

The `[PkiKey](https://github.com/PKISharp/ACMESharpCore/blob/master/src/PKISharp.SimplePKI/PkiKey.cs)` has support for exporting in both `PEM` and `DER` [encoding formats](https://github.com/PKISharp/ACMESharpCore/blob/master/src/PKISharp.SimplePKI/PkiEncodingFormat.cs).

If you use that library to generate your keys, then it's pretty straight forward to use it to export them for serialization as well as common formats like PEM and PKCS#12.

**Comment by LarryHuang77** [comment]
@kbalint, I have the same issue with your's. Did your solved the problem of exporting the private key as PEM format?

**Comment by kbalint** [comment]
@LarryHuang77 nope, didn't have the time. Started using https://github.com/fszlin/certes instead, where I can feed in an OpenSSL generated private certificate.

**Comment by LarryHuang77** [comment]
@kbalint , thank you.
