### ISSUE TITLE
Support ACME server running under path instead of root

### ISSUE THREAD

**Issue by WouterTinus** [PKISharp/ACMESharpCore#12]
We seem to hit a problem when trying the BuyPass endpoint at https://api.test4.buypass.no/acme-v02/. The library tries to find the directory under https://api.test4.buypass.no/directory instead of https://api.test4.buypass.no/acme-v02/directory

Because it's under a folder `/acme-v02/` rather than at the root of the website, I think we are running into this problem: https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working

> You must place a slash at the end of the BaseAddress, and you must not place a slash at the beginning of your relative URI, as in the following example.

In https://github.com/PKISharp/ACMESharpCore/blob/883d8c683d44409a37a834484e635bde86a28435/src/ACMESharp/Protocol/Resources/ServiceDirectory.cs we can see the Directory url hardcoded to "/directory". It think that should be "directory" and the HttpClient should make it relative to the BaseAddress.

**Comment by ebekker** [comment]
Yep, you are correct -- care to submit a PR?

**Comment by ebekker** [comment]
Actually, let's discuss how this should behave by default...

Assuming we have these combinations of inputs...
```pwsh
$bases = @(
  "http://example.com"
  "http://example.com/"
  "http://example.com/some/path"
  "http://example.com/some/path/"
)
$rels = @(
  "/directory"
  "directory"
)
```
...you'll get these combination of outputs:
```pwsh
foreach ($b in $bases) {
  foreach ($r in $rels) {
    new-object psobject -Property ([ordered]@{
      Base = $b
      BaseUri = [uri]::new($b)
      Rel = $r
      Full = [uri]::new([uri]::new($b), $r)
    })
  }
}
```
```txt
Base                          BaseUri                       Rel        Full
----                          -------                       ---        ----
http://example.com            http://example.com/           /directory http://example.com/directory
http://example.com            http://example.com/           directory  http://example.com/directory
http://example.com/           http://example.com/           /directory http://example.com/directory
http://example.com/           http://example.com/           directory  http://example.com/directory
http://example.com/some/path  http://example.com/some/path  /directory http://example.com/directory
http://example.com/some/path  http://example.com/some/path  directory  http://example.com/some/directory
http://example.com/some/path/ http://example.com/some/path/ /directory http://example.com/directory
http://example.com/some/path/ http://example.com/some/path/ directory  http://example.com/some/path/directory
```

**Comment by ebekker** [comment]
The very last combo is correct, assuming you specify a correct base path (terminated by a `/` if it has a non-root context path) or just a root URL.

**Comment by WouterTinus** [comment]
Thanks! The directory works now, but I've run into another issue creating the account. I'll create a separate issue for that.
