### ISSUE TITLE
ArgumentException on CreateAccountAsync

### ISSUE THREAD

**Issue by WouterTinus** [PKISharp/ACMESharpCore#13]
I'm running into an ArgumentException when calling `CreateAccountAsync` on the Buypass ACMEv2 endpoint (@ https://api.test4.buypass.no/acme-v02/). Seems to be an issue with a regex that gets triggered because they're doing something different than Let's Encrypt, but I haven't been able to look at the decoded JSON get to see what.

System.ArgumentException: 'Invalid Link header format Parameter name: value'

**Comment by WouterTinus** [comment]
Created a PR to solve this specific issue: #14. I'm currently not able to run most of the other integration tests (even on Let's Encrypt) so there might be more to follow.

**Comment by ebekker** [comment]
Since the associated PR has already been merged, closing out.
