### ISSUE TITLE
Once certificate is issued it needs to be loaded

### ISSUE THREAD

**Issue by dolphinsd** [PKISharp/ACMESharpCore#21]
According to msft docs, here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2

ConfigureKestrel with listenoptions needs to be called to load cert. I do not see it implemented anywhere:

As in example:
`public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureKestrel((context, options) =>
        {
            options.ListenAnyIP(5005, listenOptions =>
            {
                listenOptions.UseHttps(httpsOptions =>
                {
                    var localhostCert = CertificateLoader.LoadFromStoreCert(
                        "localhost", "My", StoreLocation.CurrentUser, 
                        allowInvalid: true);
                    var exampleCert = CertificateLoader.LoadFromStoreCert(
                        "example.com", "My", StoreLocation.CurrentUser, 
                        allowInvalid: true);
                    var subExampleCert = CertificateLoader.LoadFromStoreCert(
                        "sub.example.com", "My", StoreLocation.CurrentUser, 
                        allowInvalid: true);
                    var certs = new Dictionary<string, X509Certificate2>(
                        StringComparer.OrdinalIgnoreCase);
                    certs["localhost"] = localhostCert;
                    certs["example.com"] = exampleCert;
                    certs["sub.example.com"] = subExampleCert;

                    httpsOptions.ServerCertificateSelector = (connectionContext, name) =>
                    {
                        if (name != null && certs.TryGetValue(name, out var cert))
                        {
                            return cert;
                        }

                        return exampleCert;
                    };
                });
            });
        });`

**Comment by ebekker** [comment]
You can see the use of the `ServerCertificateSelector` in the [AcmeExtensions](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMEKestrel/AcmeExtensions.cs) extensions class, in the [ACMEKestrel](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMEKestrel) example.

Does that answer you question?

**Comment by ebekker** [comment]
I think I see what else is contributing a bit to the confusion -- the ACMEKestrel example was written for .NET Core 2.1 and your example above is from 2.2 and if you compare the two you'll see the way you configure some of the options have changed (mostly just renamed as it looks like the API is otherwise very similar):

* [Kestrel Bind to a TCP Socket in 2.1](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1#bind-to-a-tcp-socket)
* [Kestrel Bind to a TCP Socket in 2.2](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#bind-to-a-tcp-socket)

**Comment by dolphinsd** [comment]
Thanks for sharing, I will test and report back. Meantime, I will close the issue.
