### ISSUE TITLE
Implement full POST-AS-GET

### ISSUE THREAD

**Issue by monomosc** [PKISharp/ACMESharpCore#22]
Since Acme has now released as [RFC8555](https://tools.ietf.org/html/rfc8555), this Client should be updated to remove the usages of GET-Requests where the [POST-AS-GET](https://tools.ietf.org/html/rfc8555#section-6.3) Style Request should be used. Note that I can implement (and am in fact doing so in my local copy of the repo), but I will not be updating the Unittests or the Mockserver. The reason for this is that while I am relatively fluent in the protocol itself, C# is not actually my main language. My use-case for this library is testing my own implementation of the server-side of ACME.

So I guess I'm asking for whether there's interest for my changes to be merged here.

**Comment by ebekker** [comment]
Go ahead and implement what you can and submit a PR, if the tests are not updated, at least it's a start (thank you!) and myself and others can work on implementing the remainder..

**Comment by ebekker** [comment]
Any chance you can make your local changes available as a PR?  They can be implemented as an option switch on the main client library and so the unit tests should all still be valid, just need to run a few of them twice, once in each mode.

**Comment by WouterTinus** [comment]
I'm also looking forward to this being merged.

**Comment by WouterTinus** [comment]
Just created PR #27 that implements this as an optional feature. Still would be good to think about a path towards making it default.

**Comment by WouterTinus** [comment]
I don't mean to nag, but time is kind of running out on this one for the staging endpoint. Will you have time to review/merge/release this @ebekker?

**Comment by ebekker** [comment]
I've started the merge -- I'm waiting to see how the unit tests do before promoting it to a release build

**Comment by ebekker** [comment]
Thanks for the contribution, I added some integration tests to account for the POST-AS-GET and everything seems to seems to be working as expected.  The new version of the core library is 2.1.0 and it will be pushing to nuget.org shortly.
