### ISSUE TITLE
on install Deadlock detected AcmeSharpCore:String

### ISSUE THREAD

**Issue by sixerdoodle** [PKISharp/ACMESharpCore#33]
PS C:\Windows\system32> Install-Package ACMESharpCore

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'NuGet'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
Install-Package : Dependency loop detected for package 'ACMESharpCore'.
At line:1 char:1
+ Install-Package ACMESharpCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (ACMESharpCore:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by ebekker** [comment]
Are you still getting this?  I cannot reproduce it with just the steps you outlined above.  Can you provide any more details on your host configuration?  (OS version, PWSH version, architecture, etc.)

**Comment by sixerdoodle** [comment]
running windows 10 64 bit 1909 build right now, but I'm not in a place where I can attempt to reproduce.  I switched to different mechanism to get through the cert.  Since no one else appears to have reported the issue, I'm fine with closing it.
