### ISSUE TITLE
PKISharp.SimplePKI NuGet is not up to date

### ISSUE THREAD

**Issue by ronbrogan** [PKISharp/ACMESharpCore#39]
I was working on a project and found that the ability to load a `PkiCertificate` via an `X509Certificate2` instance is missing in `PKISharp.SimplePKI 1.0.1.105` package . This method is used in the CLI sample to load the public cert and export with the private key to PFX [here](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMECLI/Program.cs#L561)

It looks like once that method was added in October 2019, the package was never published with the change. Not sure if there have been other changes missed.

**Comment by ebekker** [comment]
Yes, I'm overdue to release and updated build for all the packages.  Because the existing CI pipeline (AppVeyor) is broken and I haven't had time to dig in.

I need to move the build and release process over to GitHub Actions.

**Comment by ebekker** [comment]
I've published the latest built package up to NuGet, let me know if there are any issues.  Enjoy!
