### ISSUE TITLE
Support for Azure App Services - Windows, Linux and Docker

### ISSUE THREAD

**Issue by kieronlanning** [PKISharp/ACMESharpCore#4]
Hi,

Will this work with Azure App Services - Windows, Linux and Docker instances?

For example, pushing the downloaded files to blob storage instead of the local disk, so when new instances start, they can read from the same destination?

**Comment by ebekker** [comment]
It should -- the storage of any assets generated or retrieved from the ACME CA is completely at the discretion of whatever client app is using this client lib as long as it can be stored and then recovered into the core entities (such as `AccountDetail` or `OrderDetail`).

As an experiment you could use the [CLI-based example](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMECLI) to obtain certificates and store them along with ACMESharp-generated local state to a mapped local drive backed by blob storage (using the `--state <path>` parameter).

All subsequent container instances that map to the same blob storage should be able to access all the same assets (certificate files, private certificate keys).

**Comment by kieronlanning** [comment]
Thanks @ebekker, I'll take a look.
