### ISSUE TITLE
GetAuthorizationDetailsAsync() throws AcmeProtocolException

### ISSUE THREAD

**Issue by hognevevle** [PKISharp/ACMESharpCore#42]
![image](https://user-images.githubusercontent.com/2721188/83872919-2ab69180-a733-11ea-931d-11873ea49dbf.png)

Any ideas what could be causing this?

**Comment by ebekker** [comment]
I think this is probably related to #41.

**Comment by hognevevle** [comment]
Awesome, `usePostAsGet: true` did the trick 👍 Thank you so much for the quick response!
