### ISSUE TITLE
Cannot specify certificate validity period

### ISSUE THREAD

**Issue by campler** [PKISharp/ACMESharpCore#45]
In AcmeProtocolClient, we can clearly see that code to handle validity period has been commented out ~2 years ago.
I could not find an explanation for this in commit history.

However, I would like to use this library with a different CA with our own variable validity periods.
I was wondering if there are any plans to make this functional?

**Comment by ebekker** [comment]
You're absolutely right, looks like a _TODO_ that I had left over and never got around to finishing.  Unfortunately LE does not honor any requests for a validity period since it always issues 90-day certificates no matter what, so I won't be able to test this change.

**Comment by ebekker** [comment]
Would you mind pulling down and testing [this early access build](https://www.myget.org/feed/acmesharp/package/nuget/ACMESharpCore/2.1.0.136) and testing it out for your scenario?  If you can confirm this addresses your use case, I can promote it as a stable release.

**Comment by campler** [comment]
I have tested the build and it is working as expected.

Thanks again
