### ISSUE TITLE
Missing certificate chain

### ISSUE THREAD

**Issue by franklbt** [PKISharp/ACMESharpCore#54]
Hi,

I tried to generate a new certificate using the library.
The generation in itself works well, but I couldn't find a way to fetch the full certificate chain associated with the certificate, and this behaviour is causing diverse trusting problems.

Is there a possibility to get this certificate chain ?

Thanks.

EDIT: Seems that the certificate chain is passed in the completed order.
https://community.letsencrypt.org/t/generated-certificate-is-not-trusted/139559/3

**Comment by ebekker** [comment]
Yep, glad the LE community boards were able to address this quickly for you.
