### ISSUE TITLE
Maintenance State

### ISSUE THREAD

**Issue by weldrake13** [PKISharp/ACMESharpCore#71]
Hi,

Please could you confirm if this project is actively maintained still?

I don't see any active issues outstanding but the latest commit was some time ago.

Thanks!

:)

**Comment by ebekker** [comment]
This project is still _somewhat_ maintained in that I keep an eye on any issues that come up and if there's anything that needs attention, I'll do my best to support it.  However, I won't promise that features or enhancements will be actively supported.

**Comment by weldrake13** [comment]
@ebekker thanks for the update. Please could you confirm if dependencies are kept up to date, IE in the event of CVEs, would packages be updated? 

thanks!

**Comment by ebekker** [comment]
Sadly, no, I haven't kept up with patching for dependencies, as you can [see](https://github.com/PKISharp/ACMESharpCore/pulls) on the multiple outstanding dependabot PRs.  However, if you use this lib and explicitly include all of libs that it depends on, you can be sure to use the current version which will override those that come "in the box".  Really the only dependency that seems to be out of date based on the PRs is Newtonsoft.JSON.  The LiteDB dep is only used in an example program.
